### ISSUE TITLE
Issues in documentation

### ISSUE THREAD

**Issue by johannesring** [KVSlab/VaMPy#50]
Found a few issues when following the documentation:

- SciPy was not found when running the CFD simulation as described [here](https://vampy.readthedocs.io/en/latest/getting_started.html#computational-fluid-dynamics-simulations-in-oasis). Installing SciPy should probably be part of the installation instructions.
- In Post-processing the option `--case simulation/results_artery/data/[RUN_NUMBER]/Solutions` should be `--case simulation/results_artery/artery/data/[RUN_NUMBER]/Solutions` (missing `artery`).
- Running `visualize_probes.py` gives the following error:
  ```
  $ python automatedPostProcessing/visualize_probes.py --case simulation/results_artery/artery/data/1/Solutions
  Traceback (most recent call last):
    File "automatedPostProcessing/visualize_probes.py", line 108, in <module>
      visualize_probes(folder, dt, no_of_cycles)
    File "automatedPostProcessing/visualize_probes.py", line 46, in visualize_probes
      u_probe = np.load(u, allow_pickle=True)
    File "/home/johannr/miniconda3/envs/oasis/lib/python3.8/site-packages/numpy/lib/npyio.py", line 407, in load
      fid = stack.enter_context(open(os_fspath(file), "rb"))
  FileNotFoundError: [Errno 2] No such file or directory: 'simulation/results_artery/artery/data/1/Solutions/u_x_100.probes'
  ```
  Changing `--case simulation/results_artery/artery/data/1/Solutions` to `--case simulation/results_artery/artery/data/1/Probes` (using `Probes` folder instead of `Solutions` folder) gives the following error:
  ```
  $ python automatedPostProcessing/visualize_probes.py --case simulation/results_artery/artery/data/1/Probes
  Traceback (most recent call last):
    File "automatedPostProcessing/visualize_probes.py", line 108, in <module>
      visualize_probes(folder, dt, no_of_cycles)
    File "automatedPostProcessing/visualize_probes.py", line 46, in visualize_probes
      u_probe = np.load(u, allow_pickle=True)
    File "/home/johannr/miniconda3/envs/oasis/lib/python3.8/site-packages/numpy/lib/npyio.py", line 407, in load
      fid = stack.enter_context(open(os_fspath(file), "rb"))
  FileNotFoundError: [Errno 2] No such file or directory: 'simulation/results_artery/artery/data/1/Probes/u_x_200.probes'
  ```
  There is no file `u_x_200.probes` in the results folder:
  ```
  $ find . -name "*.probes"
  ./simulation/results_artery/artery/data/1/Probes/u_y_100.probes
  ./simulation/results_artery/artery/data/1/Probes/u_x_100.probes
  ./simulation/results_artery/artery/data/1/Probes/u_z_100.probes
  ./simulation/results_artery/artery/data/1/Probes/p_100.probes
  ```

**Comment by hkjeldsberg** [comment]
Nice finds, thank you for reporting them! I have created a hotfix PR in #51. This should hopefully resolve the issues.
